/* active-round-button */

$dd_parent_selector ul.dropdown-menu.active-round-button > .current_page_item > a,
$dd_parent_selector ul.dropdown-menu.active-round-button > .current-menu-item > a {
  background-color: $dd_active_highlight_color;
  color: $dd_active_color;
}

$dd_parent_selector ul.dropdown-menu.active-round-button > li:not(.current-menu-item):not(.current_page_item):hover > a,
$dd_parent_selector ul.dropdown-menu.active-round-button > li:not(.current-menu-item):not(.current_page_item).hover > a {
  color: $dd_hover_color;
}


$dd_parent_selector .fixto-fixed ul.dropdown-menu.active-round-button > .current_page_item > a,
$dd_parent_selector .fixto-fixed ul.dropdown-menu.active-round-button > .current-menu-item > a {
  background-color: $dd_fixed_active_highlight_color;
  color: $dd_fixed_active_color;
}

$dd_parent_selector .fixto-fixed ul.dropdown-menu.active-round-button > li:not(.current-menu-item):not(.current_page_item):hover > a,
$dd_parent_selector .fixto-fixed ul.dropdown-menu.active-round-button > li:not(.current-menu-item):not(.current_page_item).hover > a {
  color: $dd_fixed_hover_color;
}


$dd_parent_selector ul.dropdown-menu.active-round-button > .current_page_item > a,
$dd_parent_selector ul.dropdown-menu.active-round-button > .current-menu-item > a {
  background-color: $dd_active_highlight_color;
  color: $dd_active_color;
}

$dd_parent_selector .fixto-fixed ul.dropdown-menu.active-round-button > .current_page_item > a,
$dd_parent_selector .fixto-fixed ul.dropdown-menu.active-round-button > .current-menu-item > a {
  background-color: $dd_fixed_active_highlight_color;
  color: $dd_fixed_active_color;
}