<?php

return array(
    
    'slide_background_type'                               => 'image',
    'slide_background_color'                              => '#6a73da',
    'slide_background_image'                              => get_template_directory_uri() . '/assets/images/home_page_header-2.jpg',
    'slide_background_image_size'                         => 'cover',
    'slide_background_image_position'                     => 'center center',
    'slide_background_video'                              => '',
    'slide_background_video_external'                     => 'https://www.youtube.com/watch?v=3iXYciBTQ0c',
    'slide_background_video_poster'                       => get_template_directory_uri() . '/assets/images/video-poster.jpg',
    'slide_background_gradient'                           => 'plum_plate',
    'slide_show_overlay'                                  => true,
    'slide_overlay_type'                                  => 'color',
    'slide_overlay_color'                                 => 'rgb(12, 0, 112)',
    'slide_overlay_gradient'                              => '{"angle":"135","colors":[{"color":"rgba(102,126,234, 0.8)","position":"0%"},{"color":"rgba(118,75,162,0.8)","position":"100%"}]}',
    'slide_overlay_opacity'                               => 0.5,
    'slide_overlay_shape'                                 => 'none',
    'slide_overlay_shape_light'                           => 0,
    'slide_content_layout'                                => 'content-on-center',
    'slide_content_media_type'                            => 'image',
    'slide_content_spacing'                               => array(
        'top'    => '14%',
        'bottom' => '14%',
    ),
    'slide_mobile_content_spacing'                        => array(
        'top'    => '10%',
        'bottom' => '10%',
    ),
    'slide_text_box_settings_text_align'                  => 'center',
    'slide_text_box_settings_text_width'                  => 85,
    'slide_text_box_settings_text_vertical_align'         => 'middle-sm',
    'slide_text_box_settings_background_color'            => 'rgba(0,0,0,0)',
    'slide_text_box_settings_background_spacing'          => array(
        'top'    => '0px',
        'bottom' => '0px',
        'left'   => '0px',
        'right'  => '0px',
    ),
    'slide_text_box_settings_background_border_radius'    => '0',
    'slide_text_box_settings_background_border_color'     => 'rgba(0,0,0,0)',
    'slide_text_box_settings_background_border_thickness' => array(
        'top'    => '0px',
        'bottom' => '0px',
        'left'   => '0px',
        'right'  => '0px',
    ),
    'slide_media_box_settings_make_image_round'           => false,
    'slide_media_box_settings_image_border_color'         => '#ffffff',
    'slide_media_box_settings_image_border_thickness'     => 5,
    'slide_media_box_settings_content_video'              => 'https://www.youtube.com/watch?v=3iXYciBTQ0c',
    'slide_media_box_settings_enable_media_shadow'        => false,
    'slide_media_box_settings_autoplay_video'             => false,
    'slide_media_box_settings_loop_video'                 => false,
    'slide_media_box_settings_video_icon_color'           => '#ffffff',
    'slide_media_box_settings_video_icon_hover_color'     => '#7AA7F5',
    'slide_media_box_settings_hide_video_poster'          => false,
    'slide_media_box_settings_video_poster'               => get_template_directory_uri() . '/assets/images/video-poster.jpg',
    'slide_media_box_settings_video_poster_overlay_color' => 'rgba(0, 0, 0, 0.5)',
    'slide_media_box_settings_media_top_bottom_width'     => 50,
    'slide_media_box_settings_media_vertical_align'       => 'middle-sm',
    'slide_media_box_settings_media_image'                => get_template_directory_uri() . '/assets/images/media-image-default.jpg',
    'slide_media_box_settings_media_left_right_width'     => 60,
    'slide_media_box_settings_media_box_spacing'          => array(
        'top'    => '0px',
        'bottom' => '0px',
    ),
    'slide_media_box_settings_frame_type'                 => 'border',
    'slide_media_box_settings_frame_width'                => 100,
    'slide_media_box_settings_frame_height'               => 100,
    'slide_media_box_settings_frame_offset_left'          => -13,
    'slide_media_box_settings_frame_offset_top'           => 10,
    'slide_media_box_settings_frame_thickness'            => 11,
    'slide_media_box_settings_frame_color'                => 'rgba(255,255,255,0.726)',
    'slide_media_box_settings_frame_show_over_image'      => false,
    'slide_media_box_settings_frame_show_shadow'          => true,
    'slide_media_box_settings_frame_hide_on_mobile'       => true,
    'slide_show_title'                                    => true,
    'slide_title_options_title_text'                      => __('You can set this title from the customizer.', 'mesmerize'),
    'slide_title_options_title_typography'                => array(
        'font-family'      => 'Muli',
        'font-weight'      => '300',
        'font-size'        => '3.3rem',
        'mobile-font-size' => '3.2em',
        'line-height'      => '114%',
        'letter-spacing'   => '0.9px',
        'text-transform'   => 'none',
        'color'            => '#ffffff',
        'subsets'          => array(),
        'addwebfont'       => true,
    ),
    'slide_title_options_title_spacing'                   => array(
        'top'    => '0px',
        'bottom' => '20px',
    ),
    'slide_title_options_background_color'                => 'rgba(0,0,0,0)',
    'slide_title_options_background_spacing'              => array(
        'top'    => '10px',
        'bottom' => '10px',
        'left'   => '20px',
        'right'  => '20px',
    ),
    'slide_title_options_background_border_radius'        => 0,
    'slide_title_options_background_border_color'         => 'rgba(0,0,0,0)',
    'slide_title_options_background_border_thickness'     => array(
        'top'    => '0px',
        'bottom' => '0px',
        'left'   => '0px',
        'right'  => '0px',
    ),
    'slide_title_options_enable_text_animation'           => false,
    'slide_title_options_text_animation_alternatives'     => "some text\nsome other text",
    'slide_show_subtitle'                                 => true,
    'slide_subtitle_options_subtitle_text'                => 'You can set this subtitle from the customizer.',
    'slide_subtitle_options_subtitle_typography'          => array(
        'font-family'      => 'Muli',
        'font-weight'      => '300',
        'font-size'        => '1.4em',
        'mobile-font-size' => '1.4em',
        'line-height'      => '130%',
        'letter-spacing'   => 'normal',
        'text-transform'   => 'none',
        'color'            => '#ffffff',
        'subsets'          => array(),
        'addwebfont'       => true,
    ),
    'slide_subtitle_options_subtitle_spacing'             => array(
        'top'    => '0px',
        'bottom' => '20px',
    ),
    'slide_subtitle_options_background_color'             => 'rgba(0,0,0,0)',
    'slide_subtitle_options_background_spacing'           => array(
        'top'    => '10px',
        'bottom' => '10px',
        'left'   => '20px',
        'right'  => '20px',
    ),
    'slide_subtitle_options_background_border_radius'     => 0,
    'slide_subtitle_options_background_border_color'      => 'rgba(0,0,0,0)',
    'slide_subtitle_options_background_border_thickness'  => array(
        'top'    => '0px',
        'bottom' => '0px',
        'left'   => '0px',
        'right'  => '0px',
    ),
    'slide_show_subtitle2'                                => false,
    'slide_subtitle2_options_subtitle2_text'              => '',
    'slide_subtitle2_options_subtitle2_typography'        => array(
        'font-family'      => 'Muli',
        'font-weight'      => '300',
        'font-size'        => '1.4em',
        'mobile-font-size' => '1.4em',
        'line-height'      => '130%',
        'letter-spacing'   => 'normal',
        'text-transform'   => 'none',
        'color'            => '#ffffff',
        'subsets'          => array(),
        'addwebfont'       => true,
    ),
    'slide_subtitle2_options_subtitle2_spacing'           => array(
        'top'    => '0px',
        'bottom' => '20px',
    ),
    'slide_subtitle2_options_background_color'            => 'rgba(0,0,0,0)',
    'slide_subtitle2_options_background_spacing'          => array(
        'top'    => '10px',
        'bottom' => '10px',
        'left'   => '20px',
        'right'  => '20px',
    ),
    'slide_subtitle2_options_background_border_radius'    => 0,
    'slide_subtitle2_options_background_border_color'     => 'rgba(0,0,0,0)',
    'slide_subtitle2_options_background_border_thickness' => array(
        'top'    => '0px',
        'bottom' => '0px',
        'left'   => '0px',
        'right'  => '0px',
    ),
    'slide_show_buttons'                                  => true,
    'slide_buttons_options_buttons_type'                  => 'normal',
    'slide_buttons_options_normal_buttons'                => array(
        0 => array(
            'label'  => 'Action Button 1',
            'url'    => '#',
            'target' => '_self',
            'class'  => 'button big color1 round',
        ),
        1 => array(
            'label'  => 'Action Button 2',
            'url'    => '#',
            'target' => '_self',
            'class'  => 'button big color-white round outline',
        ),
    ),
    'slide_buttons_options_store_buttons'                 => array(
        0 => array(
            'store' => 'google-store',
            'link'  => '#',
        ),
        1 => array(
            'store' => 'apple-store',
            'link'  => '#',
        ),
    ),
    'slide_buttons_options_background_color'              => 'rgba(0,0,0,0)',
    'slide_buttons_options_background_spacing'            => array(
        'top'    => '10px',
        'bottom' => '10px',
        'left'   => '20px',
        'right'  => '20px',
    ),
    'slide_buttons_options_background_border_radius'      => 0,
    'slide_buttons_options_background_border_color'       => 'rgba(0,0,0,0)',
    'slide_buttons_options_background_border_thickness'   => array(
        'top'    => '0px',
        'bottom' => '0px',
        'left'   => '0px',
        'right'  => '0px',
    ),

);
